apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: nginx
        image: subham258/sonu:v-1
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: site-data      
