apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: site-data      
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: task-pv-claim  
