apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: httpd
        image: nginx:1.14.2
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: site-data      
